### ISSUE TITLE
Color temperature setting

### ISSUE THREAD

**Issue by albfan** [albfan/gnome-tweak-tool#4]
Just an example of kind of discuss needed to locate right place for settings

https://bugzilla.gnome.org/show_bug.cgi?id=699250
https://bugzilla.gnome.org/show_bug.cgi?id=781473

**Comment by albfan** [comment]
http://www.omgubuntu.co.uk/2017/02/gnome-night-light-blue-light-filter-linux

**Comment by TingPing** [comment]
Personally I hope this lands in gcc.

**Comment by albfan** [comment]
Me too. Just looking for a non trivial setting to add as an example

**Comment by jbicha** [comment]
Trivial commits **are** probably better for getting started contributing.

The tricky part about this one is that this feature could still land in gnome-control-center 3.26 directly so it may end up not being needed here.

**Comment by albfan** [comment]
@jbicha ok. My only intention was to define middle goals for gnome-tweak-tool. As long as they are defined  we can close all this stuff and come back to bugzilla.

I just feel more comfortable talking about changes on a branch that you can directly execute (although finally discarted)

for example, allan day talk about a blog post about gnome-tweak-tool, and I feel like we need to clarify differences from gnome-tweak-tool, gnome-control-center and dconf-editor (not what they are now, but what we want to be in middle/long term). @allanday A post about all that could be just great

**Comment by albfan** [comment]
Let's start with #2 and see how to include this in g-t-t or g-c-c (or a direct config tool) after firsts contributions
