### ISSUE TITLE
Remove "Global Dark Theme" option

### ISSUE THREAD

**Issue by TingPing** [albfan/gnome-tweak-tool#5]
This is a very commonly used feature but its entirely mis-understood and has major downsides. It cannot ever possibly work in Flatpak and it cannot work with a toolkit other than Gtk3+.

The proper solution to this is to use -Dark versions of the theme such as Adwaita-Dark, Breeze-Dark, etc.

The one problem is how to transition users from the current method to the correct one. Also sadly some themes don't have dark versions like that, but I think those should be fixed upstream.

**Comment by albfan** [comment]
Maybe offer only if it is already used with a warn icon.

When user deselect it do not offer again (or warn everytime user choose it if offered)

**Comment by TingPing** [comment]
I think in the common case we can auto convert it:

```python
 if prefer_dark and have_theme(current_theme + '-Dark'):
     current_theme = current_theme + '-Dark'
     prefer_dark = False
```

If they don't have that then yes we can probably leave it there with a warning.

**Comment by albfan** [comment]
Sounds great.

**Comment by jbicha** [comment]
Why do you two have your own separate bug tracker?

**Comment by albfan** [comment]
Jbicha just to start this stagnated thing. Once started we can turn back to bugzilla and cgit.

I'm afraid we all can see progress in all that open bugs (with patched here and there) so a git fork with full permissions sounds an easy way to go forward

**Comment by jbicha** [comment]
Start what stagnated thing? Did you look at https://git.gnome.org/browse/gnome-tweak-tool/log this week?

And I'm afraid I don't understand your second sentence either.

You can create a wip/ branch on git.gnome.org and you have full permissions to do whatever with that branch.

But it feels to me like you two are working outside GNOME. For instance, I was just discussing this very issue (deprecating Global Dark Theme option) on #control-center on irc.gnome.org yesterday with the de facto gnome-tweak-tool maintainer. I was intending to file a bug on bugzilla with my proposal for this, maybe later today.

**Comment by TingPing** [comment]
For what its worth they approached me saying its unmaintained, I certainly didn't intend on stepping on anybodies toes.

**Comment by jbicha** [comment]
Who is "they"? TingPing, are you wanting to be the new Tweak Tool maintainer?

**Comment by sramkrishna** [comment]
@jbicha apparently, gnome-tweak-tool doesn't have a maintainer so TingPing and I are volunteering to take over maintainership and @albfan is helping out in the UI part.  The fork is really about tracking issues that we want to do going forward.

**Comment by TingPing** [comment]
@sramkrishna brought it up like a week ago, @albfan has been making this repo and everything. If a maintainer was needed I said I'd co-maintain it with them. @jbicha Since you seem to be doing good work already perhaps you are up to it?

**Comment by albfan** [comment]
@jbicha Thanks for taking time to clarify things. I just know about a "supposed" unmaintained project that seems affordable to contribute too.

Maybe @nzjrs can help us to put things in order.

We can collaborate to update wiki about gnome-tweak-tool and write a roadmap for good stuff to land on gnome-tweak-tool https://wiki.gnome.org/action/show/Apps/GnomeTweakTool like https://wiki.gnome.org/Apps/Builder/Roadmap

About this issue. @jbicha, any recommendations? we will provide a patch on bugzilla as last step

**Comment by jbicha** [comment]
nzjrs is the creator of Tweak Tool but basically he isn't maintaining it now. The current interim maintainer is Rui Matos (rtcm).

**Comment by albfan** [comment]
Ok. I joined to irc control-center channel and ask for basic help. I will ping them about this later

**Comment by albfan** [comment]
@TingPing, How do you feel about adding this to a bugzilla issue? I'm ok with any decision you made about this.

**Comment by jbicha** [comment]
@albfan @TingPing Here's my proposal:

https://bugzilla.gnome.org/783666

**Comment by albfan** [comment]
I think we can close this then
